# 3. Basic linear algebra with Numpy

## Matrices and vectors

In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

In [3]:
b = np.array([[1],
 [2],
 [3]])

In [4]:
print(A.shape,b.shape)

(3, 3) (3, 1)


## Basic operations

In [5]:
print(2*b)
print(A*b)
print(np.multiply(A,b))
print(A+3*A)

[[2]
 [4]
 [6]]
[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]
[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]
[[ 4  8 12]
 [16 20 24]
 [28 32 36]]


In [6]:
print(A.T) # Matrix transpose
print(b.T.shape)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
(1, 3)


## Determinant and inverse

In [7]:
print(np.linalg.inv(A)) # what happened?

LinAlgError: Singular matrix

In [ ]:
print(np.linalg.det(A))

In [ ]:
M = np.floor(255*np.random.random((3,3)))
print(M)
print(np.linalg.det(M))
print(np.linalg.inv(M))

## Eigenvalues and Eigenvectors

In [ ]:
eigvals, eigvecs = np.linalg.eig(M)

print(eigvals)
print(eigvecs)