# 3. Basic linear algebra with Numpy

## Matrices and vectors

In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

In [3]:
b = np.array([[1],
 [2],
 [3]])

In [4]:
print(A.shape,b.shape)

(3, 3) (3, 1)


## Basic operations

In [5]:
print(2*b)
print(A*b)
print(np.multiply(A,b))
print(A+3*A)

[[2]
 [4]
 [6]]
[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]
[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]
[[ 4  8 12]
 [16 20 24]
 [28 32 36]]


In [6]:
print(A.T) # Matrix transpose
print(b.T.shape)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
(1, 3)


## Determinant and inverse

In [7]:
print(np.linalg.inv(A)) # what happened?

LinAlgError: Singular matrix

In [8]:
print(np.linalg.det(A))

0.0


In [9]:
M = np.floor(255*np.random.random((3,3)))
print(M)
print(np.linalg.det(M))
print(np.linalg.inv(M))

[[231. 216.  22.]
 [113. 130. 113.]
 [ 29. 182.  34.]]
-3482253.9999999967
[[ 0.00463665  0.00095915 -0.00618795]
 [ 0.00016225 -0.00207222  0.0067821 ]
 [-0.00482331  0.01027438 -0.00161447]]


## Eigenvalues and Eigenvectors

In [10]:
eigvals, eigvecs = np.linalg.eig(M)

print(eigvals)
print(eigvecs)

[379.54222291 103.8257917  -88.36801461]
[[-0.79186757 -0.70168839  0.32817453]
 [-0.5104131   0.34991974 -0.56251616]
 [-0.33529721  0.62063643  0.75886563]]
